Adam
jwojciec/training pull request #2
Opened 2017-12-03 19:37 UTC by aaroslanow

hopefully good job :)

2017-12-03 20:08 UTC, jaroslaw-wojciechowski reviewed
good job 👍 ,
just some comments about formatting.

2017-12-03 20:08 UTC, jaroslaw-wojciechowski commented on src/main/java/com/example/training/controllers/UserController.java
> +    @RequestMapping(value = "/add",method = RequestMethod.POST)
new line before new method

2017-12-03 20:08 UTC, jaroslaw-wojciechowski commented on src/main/java/com/example/training/controllers/UserController.java
> +    public void deleteUser(@PathVariable int id) { repository.deleteUser(id); }
don't use one-liners. This would be easier to read:

```
@RequestMapping(value = "/delete/{id}", method = RequestMethod.DELETE)
public void deleteUser(@PathVariable int id) {
    repository.deleteUser(id);
}
```

2017-12-03 20:08 UTC, jaroslaw-wojciechowski commented on src/main/java/com/example/training/model/User.java
> +import java.io.Serializable;
do You need Serializable?

2017-12-03 20:08 UTC, jaroslaw-wojciechowski commented on src/main/java/com/example/training/model/User.java
> +    public User(String id, String name, String surname)  {
please reformat code with: Menu => Code => Reformat Code

2017-12-03 20:08 UTC, jaroslaw-wojciechowski commented on src/main/java/com/example/training/repository/SimpleListRepository.java
> +    public void deleteUser(int id) { USER_LIST.remove(id);}
please reformat code

2017-12-03 20:08 UTC, jaroslaw-wojciechowski commented on src/test/java/com/example/training/controllers/UserControllerTest.java
> +    @Test
remove comments (like //ToDo)

2017-12-03 20:08 UTC, jaroslaw-wojciechowski commented on src/test/java/com/example/training/controllers/UserControllerTest.java
> +    private static final User TEST_USER_TO_ADD = new User("8644d523-eaf2-412b-87349-82ceba72ec6b","Jakub","Przybyla");
reformat code

2017-12-03 20:08 UTC, jaroslaw-wojciechowski commented on src/test/java/com/example/training/controllers/UserControllerTest.java
> +    ObjectMapper objectMapper = new ObjectMapper();
objectMapper can should be private static final.
Then rename to OBJECT_MAPPER as it's constant variable.

2017-12-03 20:08 UTC, jaroslaw-wojciechowski commented on src/test/java/com/example/training/repository/SimpleListRepositoryTest.java
> +    private static final User NEW_TEST_USER = new User("5", "Jim", "Ziggy");
please add new line before test.

2017-12-03 20:08 UTC, jaroslaw-wojciechowski commented on src/test/java/com/example/training/repository/SimpleListRepositoryTest.java
> +    }
please add new line before new test.

2017-12-03 20:08 UTC, jaroslaw-wojciechowski commented on src/test/java/com/example/training/repository/SimpleListRepositoryTest.java
> +        // rollback new user
delete all comments. It's clear when you read this code.
Use comments only for some bug work-arounds or some specific algorithms.

2017-12-03 20:08 UTC, jaroslaw-wojciechowski commented on src/test/java/com/example/training/repository/SimpleListRepositoryTest.java
> +        REPOSITORY.deleteUser(4);
user private static final variable like NEW_TEST_USER_ID for better readability.

2017-12-03 20:09 UTC, jaroslaw-wojciechowski requested changes
Please apply fixes after code review.

2017-12-04 17:55 UTC, jwojciec requested changes

2017-12-04 17:55 UTC, jwojciec commented on src/test/java/com/example/training/controllers/UserControllerTest.java
> +    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();
move OBJECT_MAPPER before mockMvc.
private static final should be before private

2017-12-04 17:55 UTC, jwojciec commented on src/test/java/com/example/training/TrainingApplicationTests.java
> +    }
empty line 15 not needed

2017-12-04 17:55 UTC, jwojciec commented on src/main/java/com/example/training/repository/SimpleListRepository.java
> +
empty line not needed

2017-12-04 17:55 UTC, jwojciec commented on src/main/java/com/example/training/model/User.java
> +
empty line not needed

2017-12-04 20:23 UTC, jwojciec approved these changes

2017-12-04 20:24 UTC, merged